[package]
name = "scarb_dependencias"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
math_scarb = { git = "https://github.com/dpinones/math_scarb.git", rev = "f97ef25" }

[scripts]
test = "cairo-test ."
